### ISSUE TITLE
Make it work with projects using Babel 7

### ISSUE THREAD

**Issue by tzimmermann** [signavio/i18n#36]
Not sure yet how much work this will be, but would be nice to have this lib working with babel 7.
I'll investigate a bit if I find the time, but if anyone has an idea, please spread the knowledge 😃  

It's currently the last blocker for us to upgrade our project to the new babel version.

Current error when running the `i18n-extract` script:

```
$ i18n-extract "src/**/*.js" src/locales/messages.pot && i18n-merge src/locales/messages.pot src/locales/*.po
/Users/tz-mac/Repos/pex-client/node_modules/@babel/helper-plugin-utils/lib/index.js:72
  throw Object.assign(err, {
  ^

Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.0". If you are sure you have a compatibleversion of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
```

**Comment by tzimmermann** [comment]
Thinking about it, it seems like a bug to me.
Shouldn't the i18n `extract.js` script use its own `babel-core: ^6.2.1` version (as found in the package.json)?
Right now, it looks like it is being implicitly relying on babel-core in the project that is using `signavio-i18n`.

Here's the full stack trace. Looks wrong to me that at some point, it switches from using its own `babel-core`:
`pex-client/node_modules/signavio-i18n/node_modules/babel-core`
to the one we have in `pex-client`:
`pex-client/node_modules/@babel/helper-plugin-utils/lib/`

```
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.0". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/Users/tz-mac/Repos/pex-client/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/tz-mac/Repos/pex-client/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/tz-mac/Repos/pex-client/node_modules/@babel/plugin-proposal-class-properties/lib/index.js:81:7)
    at /Users/tz-mac/Repos/pex-client/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/Users/tz-mac/Repos/pex-client/node_modules/signavio-i18n/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/tz-mac/Repos/pex-client/node_modules/signavio-i18n/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/tz-mac/Repos/pex-client/node_modules/signavio-i18n/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/tz-mac/Repos/pex-client/node_modules/signavio-i18n/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/tz-mac/Repos/pex-client/node_modules/signavio-i18n/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/tz-mac/Repos/pex-client/node_modules/signavio-i18n/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/tz-mac/Repos/pex-client/node_modules/signavio-i18n/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/tz-mac/Repos/pex-client/node_modules/signavio-i18n/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/tz-mac/Repos/pex-client/node_modules/signavio-i18n/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transformFileSync (/Users/tz-mac/Repos/pex-client/node_modules/signavio-i18n/node_modules/babel-core/lib/api/node.js:152:10)
    at /Users/tz-mac/Repos/pex-client/node_modules/signavio-i18n/lib/scripts/extract.js:64:36
    at arrayEach (/Users/tz-mac/Repos/pex-client/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/tz-mac/Repos/pex-client/node_modules/lodash/forEach.js:38:10)
    at Object.<anonymous> (/Users/tz-mac/Repos/pex-client/node_modules/signavio-i18n/lib/scripts/extract.js:51:20)
    at Module._compile (module.js:652:30)
```

Any ideas @jfschwarz @TimKam ?

**Comment by jfschwarz** [comment]
Since the source files from which we extract have to be parsed using the settings of the project's .babelrc and since the syntax of the .babelrc obviously has to be compatible with the project's babel version, we must make babel-core a peer dependency.

Hope this makes sense. Could you submit a PR, @tzimmermann? Optimally we support babel 6 and 7 as a peer dep. If that turns out difficult we can also just support babel-core@7. It will be a new major release of signavio-i18n in any case.
